# Generated by Django 4.2.16 on 2024-11-13 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0005_equipe_github_equipe_google_scholar_equipe_lattes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monografias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('discente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipe.equipe')),
            ],
        ),
    ]
