# Generated by Django 4.2.16 on 2024-11-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0005_equipe_github_equipe_google_scholar_equipe_lattes_and_more'),
        ('monografias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monografias',
            name='coorientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coorientador', to='equipe.equipe'),
        ),
        migrations.AddField(
            model_name='monografias',
            name='dat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monografias',
            name='orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to='equipe.equipe'),
        ),
    ]
