# Generated by Django 4.2.16 on 2024-11-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='formacao_academica',
            field=models.CharField(choices=[('G', 'Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado')], default='G', max_length=30),
        ),
    ]
