# Generated by Django 4.2.16 on 2024-11-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_equipe_formacao_academica'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
