# Generated by Django 4.2.16 on 2024-11-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_equipe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='registro_atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='registro_criado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
