# Generated by Django 4.2.16 on 2024-11-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0004_equipe_registro_atualizado_equipe_registro_criado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='google_scholar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='lattes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='orcid',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='research_gate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='registro_criado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
