# Generated by Django 4.2.16 on 2024-11-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0005_equipe_github_equipe_google_scholar_equipe_lattes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='github',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='google_scholar',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='lattes',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='orcid',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='research_gate',
        ),
    ]
